/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Implementation.FuncionarioImpl;
import DAO.Interface.FuncionarioDao;
import DAO.ValueObject.Funcionario;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jenny_izquierdo
 */
public final class FrmCreateFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmCreateFuncionarios
     */
    public FrmCreateFuncionarios() {
        initComponents();
        clearComponents();
        
        // Call Implementation DAO
        FuncionarioDao funcionariosDao = null;
        
        // Call Populate Info
        populateComboBox(funcionariosDao);
        
        // Set names components
        jLblTitle.setText("Nuevo Registro");
        jBtnGuardar.setText("Guardar");
        jBtnCancelar.setText("Cancelar");
        jFormattedFechaNac.setText("YYYY-MM-DD Ex: 2023-05-30");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCreateFuncionarios = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jSeparatorPanel = new javax.swing.JSeparator();
        jPanelInfoBasica = new javax.swing.JPanel();
        jTextNombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNumeroId = new javax.swing.JTextField();
        cmbTipoId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedFechaNac = new javax.swing.JTextField();
        jPanelDatosContacto = new javax.swing.JPanel();
        jTextDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoVia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        lblImageUserInterface = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLblTitle.setText("jLabel1");

        jPanelInfoBasica.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informacion Personal"));

        jTextNombres.setText("jTextField1");
        jTextNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombresActionPerformed(evt);
            }
        });
        jTextNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombresKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jTextApellidos.setText("jTextField1");
        jTextApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidosKeyTyped(evt);
            }
        });

        jLabel3.setText("Tipo Identificacion");

        jLabel4.setText("Numero Identificacion");

        jTextNumeroId.setText("jTextField1");

        cmbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIdActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado Civil");

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Sexo");

        jLabel7.setText("Fecha de Nacimiento");

        jFormattedFechaNac.setText("jTextField1");
        jFormattedFechaNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedFechaNacMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFormattedFechaNacMouseExited(evt);
            }
        });
        jFormattedFechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedFechaNacKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoBasicaLayout = new javax.swing.GroupLayout(jPanelInfoBasica);
        jPanelInfoBasica.setLayout(jPanelInfoBasicaLayout);
        jPanelInfoBasicaLayout.setHorizontalGroup(
            jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jTextNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(cmbTipoId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jTextNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
        );
        jPanelInfoBasicaLayout.setVerticalGroup(
            jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelDatosContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Contacto"));

        jTextDireccion.setText("jTextField1");

        jLabel8.setText("Dirección");

        cmbTipoVia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Telefono");

        jTextTelefono.setText("jTextField1");

        javax.swing.GroupLayout jPanelDatosContactoLayout = new javax.swing.GroupLayout(jPanelDatosContacto);
        jPanelDatosContacto.setLayout(jPanelDatosContactoLayout);
        jPanelDatosContactoLayout.setHorizontalGroup(
            jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                        .addComponent(cmbTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanelDatosContactoLayout.setVerticalGroup(
            jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblImageUserInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user-interface.png"))); // NOI18N

        jBtnGuardar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnGuardar.setText("jButton1");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("jButton1");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCreateFuncionariosLayout = new javax.swing.GroupLayout(jPanelCreateFuncionarios);
        jPanelCreateFuncionarios.setLayout(jPanelCreateFuncionariosLayout);
        jPanelCreateFuncionariosLayout.setHorizontalGroup(
            jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateFuncionariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanelCreateFuncionariosLayout.createSequentialGroup()
                .addGroup(jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCreateFuncionariosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jLblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112)
                        .addComponent(lblImageUserInterface))
                    .addGroup(jPanelCreateFuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelInfoBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelCreateFuncionariosLayout.setVerticalGroup(
            jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateFuncionariosLayout.createSequentialGroup()
                .addGroup(jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCreateFuncionariosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateFuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImageUserInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanelInfoBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelCreateFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnGuardar))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCreateFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCreateFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // Check all fields
        
        //Recopile records
        
        String nombres = jTextNombres.getText();
        String apellidos = jTextApellidos.getText();
        String direccion = jTextDireccion.getText();
        String numeroId = jTextNumeroId.getText();
        String tipoId = cmbTipoId.getSelectedItem().toString();
        String estadoCivil = cmbEstadoCivil.getSelectedItem().toString();
        String sexo = cmbSexo.getSelectedItem().toString();
        String tipoVia = cmbTipoVia.getSelectedItem().toString();        
        String fecha_nac = jFormattedFechaNac.getText();
        String telefono = jTextTelefono.getText();
        
        
        // validate empty fields
        
        if (!"".equals(nombres) && !"".equals(apellidos) && !"".equals(direccion) 
                && !"".equals(numeroId) && !"Seleccionar una opcion".equals(tipoId) 
                && !"Seleccionar una opcion".equals(estadoCivil) && !"Seleccionar una opcion".equals(sexo) 
                && !"Seleccionar una opcion".equals(tipoVia) && !"".equals(fecha_nac) && !"".equals(telefono)) {
            
            // Create Funcionario Object and mapping the info
            Funcionario _funcionario = new Funcionario();
            
            _funcionario.setNombres(nombres);
            _funcionario.setApellidos(apellidos);
            _funcionario.setDireccion(tipoVia + " " +direccion);
            _funcionario.setEstadoCivil(estadoCivil);
            
            try {
                Date _fechaNac = new SimpleDateFormat("yyyy-MM-dd").parse(fecha_nac);
                _funcionario.setFechaNacimiento(_fechaNac);
            } catch (ParseException ex) {
                Logger.getLogger(FrmCreateFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            _funcionario.setSexo(sexo);
            _funcionario.setNumeroIdentificacion(numeroId);
            _funcionario.setTipoIdentificacion(tipoId);
            _funcionario.setTelefono(telefono);
            
            // Send Object
            
            try {
                FuncionarioDao funcionariosDao = new FuncionarioImpl();
                funcionariosDao.createFuncionario(_funcionario);
                
                //ok -  user
                String _message = "Usuario creado correctament";
                String _title = "Information";
                JOptionPane.showMessageDialog(null, _message, _title, JOptionPane.INFORMATION_MESSAGE); 
                clearComponents();
            } catch (HeadlessException e) {
                System.out.println(e.getMessage());
            }
        } else
        {
            String _message = "Campos vacios o sin seleccionar, por favor verifique";
            String _title = "Warning";
            JOptionPane.showMessageDialog(null, _message, _title, JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // close windows
        dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jFormattedFechaNacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedFechaNacKeyPressed

    }//GEN-LAST:event_jFormattedFechaNacKeyPressed

    private void jFormattedFechaNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedFechaNacMouseClicked
        jFormattedFechaNac.setText("");
    }//GEN-LAST:event_jFormattedFechaNacMouseClicked

    private void jFormattedFechaNacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedFechaNacMouseExited
      
    }//GEN-LAST:event_jFormattedFechaNacMouseExited

    private void jTextNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombresKeyTyped
        // TODO add your handling code here:
        jLblTitle.setText(jTextNombres.getText() +" "+ jTextApellidos.getText());
    }//GEN-LAST:event_jTextNombresKeyTyped

    private void jTextApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidosKeyTyped
        jLblTitle.setText(jTextNombres.getText() +" " +  jTextApellidos.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidosKeyTyped

    private void cmbTipoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoIdActionPerformed

    private void jTextNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombresActionPerformed

    
    public void clearComponents()
    {
        jLblTitle.setText("");
        jTextApellidos.setText("");
        jTextNombres.setText("");
        jTextDireccion.setText("");
        jTextNumeroId.setText("");
        jTextTelefono.setText("");
        jFormattedFechaNac.setText("");
        cmbTipoId.removeAllItems();
        cmbEstadoCivil.removeAllItems();
        cmbSexo.removeAllItems();
        cmbTipoVia.removeAllItems();
        
    }
    
    
    public void populateComboBox(FuncionarioDao funcionariosDao)
    {   
        // load Combox
        loadTipoId(funcionariosDao);
        loadEstadoCivil(funcionariosDao);
        loadSexo(funcionariosDao);
        loadTipoVia(funcionariosDao); 
    }
    
    
    private void loadTipoId( FuncionarioDao funcionariosDao) {
        funcionariosDao = new FuncionarioImpl();
        
        // Default Value
        cmbTipoId.addItem("Seleccionar una opcion");
        
        for (String item : funcionariosDao.getAllTipoId())
        {
            cmbTipoId.addItem(item);
        }
    }
    
     private void loadEstadoCivil( FuncionarioDao funcionariosDao) {
        funcionariosDao = new FuncionarioImpl();
        
        // Default Value
        cmbEstadoCivil.addItem("Seleccionar una opcion");
        
        for (String item : funcionariosDao.getAllEstadoCivil())
        {
            cmbEstadoCivil.addItem(item);
        }
    }
     
      private void loadSexo( FuncionarioDao funcionariosDao) {
        funcionariosDao = new FuncionarioImpl();
        
        // Default Value
        cmbSexo.addItem("Seleccionar una opcion");
        
        for (String item : funcionariosDao.getAllSexo())
        {
            cmbSexo.addItem(item);
        }
    }
      
       private void loadTipoVia( FuncionarioDao funcionariosDao) {
        funcionariosDao = new FuncionarioImpl();
        
        // Default Value
        cmbTipoVia.addItem("Seleccionar una opcion");
        for (String item : funcionariosDao.getAllTipoDirs())
        {
            cmbTipoVia.addItem(item);
        }
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreateFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbTipoId;
    private javax.swing.JComboBox<String> cmbTipoVia;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JTextField jFormattedFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanelCreateFuncionarios;
    private javax.swing.JPanel jPanelDatosContacto;
    private javax.swing.JPanel jPanelInfoBasica;
    private javax.swing.JSeparator jSeparatorPanel;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextNumeroId;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JLabel lblImageUserInterface;
    // End of variables declaration//GEN-END:variables
}
